<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
    <PackageId>Pato.Framework</PackageId>
    <Authors>Patosalvaje</Authors>
    <Version>3.4.1</Version>
    <PackageIcon>./logo.png</PackageIcon>
    <Description>A simple C# ECS Framework, implemented using SDL-CS.</Description>
  </PropertyGroup>


  <ItemGroup>
      <None Include="./logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
  </ItemGroup>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <Copy SourceFiles="./$(OutputPath)../$(PackageId).$(PackageVersion).nupkg" DestinationFolder="./Nuget/" />
  </Target>

  <PropertyGroup>
    <DefineConstants>Framework</DefineConstants>
  </PropertyGroup>


</Project>
